### ISSUE TITLE
Support for complex field types

### ISSUE THREAD

**Issue by kgoggin** [alexfedoseev/re-formality#10]
Based on my understanding of how things are set up, it looks like you can only have fields of type `string`, as that's the type of `Formality__Validation__value`, and the `get` method must return that type. It'd be really great to support more complex types. For example: a group of checkboxes whose value is represented in state as an array of the string values of the selected options. 

I noticed you have a "TODO" comment alongside that type definition so I'm guessing you've already thought of this. By using a variant there, I assume you'd seek to constrain the options available (string, int, bool, etc.)?

**Comment by alexfedoseev** [comment]
TBH I haven't put much thinking into this yet but outlined two directions to investigate:

1. Make value a variant:

```
type value =
| String(string)
| Int(int)
| Bool(bool)
...;
```

2. Define `value` type in user land (in form config).

**Comment by kgoggin** [comment]
Yeah I was thinking about it as well. It seems ideal to be able to let the user define the type, but also like that might add a lot of complexity. Also, it's kind of a pain to have to define a `value` type as the user when in the majority of cases it's just `string` - but I don't think you could default the type, right?

OTOH if you go with the basic variant you're likely to just keep having to add options to it as people encounter different use cases.

If you went with the user-defined option, I suppose the Validation module would need to change to be a functor that also took the config module so it had access to the user-defined type, right?

For now I'm just serializing my array to a string and converting it back to an array again in my submit handler, and that works okay. But, I'd love to see a good solution for this and happy to help if I can!

**Comment by alexfedoseev** [comment]
> OTOH if you go with the basic variant you're likely to just keep having to add options to it as people encounter different use cases.

Yeah, this is exactly the reason why I haven't implemented it yet. It's like rabbit hole. Also, every user gets perf penalty due to allocations, even if they don't need anything but string.

> It seems ideal to be able to let the user define the type, but also like that might add a lot of complexity.

I just checked sources real quick and it seems delegating value definition to user is not a big issue. Formality (almost) doesn't care about the value itself, it just passes things around. The only thing that abstraction cares about is `validationResult`. The rest is just abstract types.

The only thing I need in this case tho is the way to find out if value is _empty_ (to avoid emitting success on empty values, #9), but I can ask user to define this function for me in config, e.g.:

```reason
/* type */
let isEmpty = value => bool;

/* config */
let isEmpty = value => value === "";
```

I'll look into this soon, shouldn't take a long (famous last words 😂)

**Comment by alexfedoseev** [comment]
Oh well... looks like it's implemented #12

**Comment by alexfedoseev** [comment]
@kgoggin Try `0.5.0` and let me know how it works for your use cases. I'm really curious how it scales!

**Comment by kgoggin** [comment]
@alexfedoseev just upgraded and converted over my form and it's working great! Thanks so much!
