### ISSUE TITLE
Provide data on overall validation state of the form

### ISSUE THREAD

**Issue by kgoggin** [alexfedoseev/re-formality#22]
Hey, it's me again! 👋 Got another enhancement I'd like to suggest:

It'd be great if the `form` interface provided some kind of overall validation status. Basically, `true` if each field is valid, `false` if any field isn't valid. I think I could theoretically gather up the results of calling `form.status` for each field, but that seems like a pain to have to do for each field, for each form. My use case here is it'd like to disable the submit button as a visual cue to the user if the form isn't in a valid state.

What do you think of this? Happy to help implement if you think it'd make a good addition. Thanks!

**Comment by alexfedoseev** [comment]
@kgoggin Hey, sorry for a long response! I had a tough week which isn't over yet. I'll get back to you once I’m done w/ the work stuff, in the middle of the next week.

**Comment by alexfedoseev** [comment]
@kgoggin Use case is totally valid. One concern tho: proposed implementation (`bool` field on `form` record) presumes that internally container must trigger validator of each field on every update and it will affect every user even if they don't use this feature. Also, it might affect perf on long forms.

What about this: instead of actually performing validation and expose result we can expose function which returns `bool`. And if UI requires this feature developer can invoke it. Otherwise, it just sits inside the record w/o runtime overhead. We already have `fold` method in `Validators` module so we can use it.

There are also async validators but I think we should just ignore them in this case?

**Comment by alexfedoseev** [comment]
Alright, can you work on this?

**Comment by kgoggin** [comment]
Sure! Not sure how quickly I'll be able to get to it but I'd be happy to take a shot at it!

**Comment by alexfedoseev** [comment]
Awesome! No rush 😄
